name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: dongjukim123/nodejs-ci
          tags: |
            latest
            {{version}}
            {{major}}.{{minor}}

      - name: Print Tags
        run: echo "${{ steps.docker_meta.outputs.tags }}"

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            dongjukim123/nodejs-ci:latest
            ${{ steps.docker_meta.outputs.tags }} 
          labels: ${{ steps.docker_meta.outputs.labels }}
