name: Push Docker Image to Docker Hub

on:
  push:
    branches:
      - 'main'
    tags:
      - '**'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: dongjukim123/nodejs-ci
          tags: |
            latest
            {{version}}
            {{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            dongjukim123/nodejs-ci:latest
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Save state and set output using environment files
        run: |
          echo "MY_OUTPUT=some_value" >> $GITHUB_OUTPUT
          echo "MY_STATE=some_state_value" >> $GITHUB_STATE
